version: '3.8'

services:
  metabase:
    image: metabase/metabase:v0.48.0
    container_name: data-hub-metabase
    ports:
      - "3000:3000"
    environment:
      # Configurações básicas
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: host.docker.internal
      
      # Configurações de performance
      JAVA_OPTS: -Xmx2g -XX:+UseG1GC
      
      # Configurações opcionais
      MB_SITE_NAME: "Data Hub Analytics"
      MB_SITE_LOCALE: "pt"
      MB_TIMEZONE: "America/Recife"
      
      # Desabilitar analytics do Metabase (opcional)
      MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE: false
      MB_ANON_TRACKING_ENABLED: false
      
    volumes:
      - metabase_data:/metabase-data
    
    depends_on:
      - metabase-db
    
    networks:
      - metabase-network
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  metabase-db:
    image: postgres:15-alpine
    container_name: data-hub-metabase-db
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
    networks:
      - metabase-network
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  metabase_data:
    driver: local
  metabase_db_data:
    driver: local

networks:
  metabase-network:
    driver: bridge