data_hub:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 54322
      user: postgres
      pass: postgres
      dbname: postgres
      schema: analytics
      threads: 4
      keepalives_idle: 0
      
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASS') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: analytics
      threads: 8
      keepalives_idle: 0
      
  target: dev